[package]
name = "anon_billboard_contract"
type = "contract"
authors = [""]
compiler_version = ">=1.0.0"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-nr", tag = "v4.3.0", directory = "aztec" }
balance_set = { git = "https://github.com/AztecProtocol/aztec-nr", tag = "v4.3.0", directory = "balance-set" }
token_contract = { path = "../token_contract" }
