[package]
name = "fee_nested"
type = "contract"
authors = [""]
compiler_version = ">=1.0.0"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-nr", tag = "v5.2.0", directory = "aztec" }
fee_sponsor = { path = "../sponsor" }
fee_target = { path = "../application" }
