[package]
name = "billboard_test"
authors = [""]
compiler_version = ">=1.0.0"
type = "lib"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-nr", tag = "v5.0.0", directory = "aztec" }
billboard_contract = { path = "../billboard_contract" }
