[package]
name = "billboard_test"
authors = [""]
compiler_version = ">=1.0.0"
type = "lib"

[dependencies]
aztec = { git = "https://github.com/aztec-labs-eng/aztec-nr", tag = "v6.0.0-rc.1", directory = "aztec" }
billboard_contract = { path = "../billboard_contract" }
