[profile.default]
src = "src"
out = "out"
libs = ["node_modules/@aztec/l1-artifacts/l1-contracts", "lib"]
solc = "0.8.27"
evm_version = "prague"
optimizer = true

remappings = [
    "@aztec/=node_modules/@aztec/l1-artifacts/l1-contracts/src/",
    "@aztec-blob-lib/=node_modules/@aztec/l1-artifacts/l1-contracts/src/core/libraries/rollup/",
    "@oz/=node_modules/@aztec/l1-artifacts/l1-contracts/lib/openzeppelin-contracts/contracts/",
]
