[package]
name = "private_fee_test"
type = "lib"
authors = [""]
compiler_version = ">=1.0.0"

[dependencies]
aztec = { git = "https://github.com/aztec-labs-eng/aztec-nr", tag = "v6.0.0-rc.1", directory = "aztec" }
private_fee_contract = { path = "../private_fee_contract" }
